apiVersion: batch/v1
kind: Job
metadata:
  name: math-add-job
spec:
  completions: 3 # Specifies that this Job must have 3 successful completions
  parallelism: 3 # Specifies that this Job must spin up 3 Pods in parallel
  template:
    spec:
      containers:
        - name: math-add
          image: ubuntu
          command: [ 'expr', '2', '+','2' ]
      restartPolicy: Never