apiVersion: v1
kind: ConfigMap
metadata:
  name: myapp-configmap
data:
  HOST: "localhost"
  PORT: "6379"
  ENABLED: "true"
---
apiVersion: v1
kind: Pod
metadata:
  name: myapp-with-vars
  labels:
    app: myapp-with-vars
    type: front-end
spec:
  containers:
    - name: nginx-container
      image: nginx
      env:
        - name: MY_ENV_VAR
          value: some-value
        - name: ANOTHER_VAR
          value: some-other-value
      envFrom:
        - configMapRef:
            name: myapp-configmap # name of configmap as identifier
